apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rhtap-pr-validation
  namespace: rhtap-staging-testing
spec:
  params:
    - name: repo_url
    - name: revision
    - name: pull_request_number
    - name: source_branch
  workspaces:
    - name: git
    - name: shared-file
  tasks:
    - name: clone-infra-deployment-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.revision)
        - name: depth
          value: "3"
      workspaces:
      - name: output
        workspace: git
        subPath: infra-deployment-git
    - name: get-pr-modified-files
      taskRef:
        name: get-pr-modified-files
      runAfter:
        - clone-infra-deployment-git
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
        - name: shared-file-path
          workspace: shared-file
    - name: validate-pr-restriction
      taskRef:
        name: pr-restriction
      runAfter:
        - get-pr-modified-files
      workspaces:
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
        - name: shared-file-path
          workspace: shared-file
    - name: get-github-token
      taskRef:
        name: get-github-token
      runAfter:
        - validate-pr-restriction
      workspaces:
        - name: shared-file-path
          workspace: shared-file
        - name: infra-deployment-git
          workspace: git
          subPath: infra-deployment-git
    - name: reject-pr
      taskRef:
        name: reject-pr
      params:
        - name: pull_request_number
          value: $(params.pull_request_number)
        # - name: source_branch
        #   value: $(params.source_branch)
      when:
        - $(tasks.validate-pr-restriction.results.is_valid) == "False"
      runAfter:
        - get-github-token
      workspaces:
        - name: shared-file-path
          workspace: shared-file